# -*- coding: utf-8 -*-
"""CRUD-sqlite3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hF9Fvn58YvRwBExN8RzCDrqh7fxUMkqR
"""

import sqlite3 as sql

con = sql.connect("works.db")
cursor = con.cursor()

# CREATE (C)

cursor.execute('''
  create table if not exists workers (
    id int primary key,
    name varchar(255) not null,
    age int check (age > 18))''')

def add_worker(id, name, age):
    cursor.execute('INSERT INTO workers (id, name, age) VALUES (?, ?, ?)', (id, name, age))
    con.commit()

add_worker(1, 'Sarah', 25)
add_worker(2, 'Malena', 23)
add_worker(3, 'Simon', 42)
add_worker(4, 'Dominic', 37)
add_worker(5, 'Peter', 34)

# READ (R)

def read_workers():
    cursor.execute('SELECT * FROM workers')
    return cursor.fetchall()
print(f"All workers: {read_workers()}")

# UPDATE (U)

def update_workers(w_id, new_name, new_age):
    cursor.execute('UPDATE workers SET name = ?, age = ? WHERE id = ?', (new_name, new_age, w_id))
    con.commit()

update_workers(3, 'Alicia', 30)
print("Updated Students:", read_workers())

# DELETE (D)

def delete_worker(w_id):
    cursor.execute('DELETE FROM workers WHERE id = ?', (w_id,))
    con.commit()

delete_worker(4)
print(f"After: {read_workers()}")

con.close()